networks:
  networkDevicesMySqlSpringboot:
    external: true
volumes:
  mysql_data_springboot:
    external: true
  postgresql_data_springboot:
    external: true
  mysql_db_admin_springboot:
    external: true
  postgresql_db_admin_springboot:
    external: true
services:
  db_mysql_springboot:
    image: mysql:8.0
    container_name: mySql_db
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    networks:
      networkDevicesMySqlSpringboot:
        ipv4_address: 100.188.0.11
    #restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: "dbMySqlPassRoot"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql_data_springboot:/var/lib/mysql

  phpmyadmin_springboot:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin_admin
    environment:
      PMA_HOST: db_link_mysql
    networks:
      networkDevicesMySqlSpringboot:
        ipv4_address: 100.188.0.10
    #restart: always
    ports:
      - "8082:80"
    expose:
      - "80"
    links:
      - db_mysql_springboot:db_link_mysql
    depends_on:
      - db_mysql_springboot
  db_postgres_springboot:
    container_name: postgres_db
    image: postgres:15
    networks:
      networkDevicesMySqlSpringboot:
        ipv4_address: 100.188.0.13
    #restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    expose:
      - "5432"
    volumes:
      - postgresql_data_springboot:/var/lib/postgresql/data/

  pgadmin_springboot:
    image: dpage/pgadmin4:9.2
    container_name: pgadmin_admin
    networks:
      networkDevicesMySqlSpringboot:
        ipv4_address: 100.188.0.12
    #restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - postgresql_db_admin_springboot:/var/lib/pgadmin
    depends_on:
      - db_postgres_springboot
